/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	myappdeploymentv1alpha1 "sample-controller-k8s/pkg/apis/myappdeployment/v1alpha1"
	versioned "sample-controller-k8s/pkg/clinet/clientset/versioned"
	internalinterfaces "sample-controller-k8s/pkg/clinet/informers/externalversions/internalinterfaces"
	v1alpha1 "sample-controller-k8s/pkg/clinet/listers/myappdeployment/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MyAppDeploymentInformer provides access to a shared informer and lister for
// MyAppDeployments.
type MyAppDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MyAppDeploymentLister
}

type myAppDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyAppDeploymentInformer constructs a new informer for MyAppDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyAppDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyAppDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyAppDeploymentInformer constructs a new informer for MyAppDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyAppDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NextgenV1alpha1().MyAppDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NextgenV1alpha1().MyAppDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&myappdeploymentv1alpha1.MyAppDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *myAppDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyAppDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myAppDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&myappdeploymentv1alpha1.MyAppDeployment{}, f.defaultInformer)
}

func (f *myAppDeploymentInformer) Lister() v1alpha1.MyAppDeploymentLister {
	return v1alpha1.NewMyAppDeploymentLister(f.Informer().GetIndexer())
}
