/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MyAppDeploymentSpecApplyConfiguration represents an declarative configuration of the MyAppDeploymentSpec type for use
// with apply.
type MyAppDeploymentSpecApplyConfiguration struct {
	DeploymentName  *string `json:"deploymentName,omitempty"`
	DeploymentImage *string `json:"deploymentImage,omitempty"`
	Replicas        *int32  `json:"replicas,omitempty"`
}

// MyAppDeploymentSpecApplyConfiguration constructs an declarative configuration of the MyAppDeploymentSpec type for use with
// apply.
func MyAppDeploymentSpec() *MyAppDeploymentSpecApplyConfiguration {
	return &MyAppDeploymentSpecApplyConfiguration{}
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *MyAppDeploymentSpecApplyConfiguration) WithDeploymentName(value string) *MyAppDeploymentSpecApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithDeploymentImage sets the DeploymentImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentImage field is set to the value of the last call.
func (b *MyAppDeploymentSpecApplyConfiguration) WithDeploymentImage(value string) *MyAppDeploymentSpecApplyConfiguration {
	b.DeploymentImage = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *MyAppDeploymentSpecApplyConfiguration) WithReplicas(value int32) *MyAppDeploymentSpecApplyConfiguration {
	b.Replicas = &value
	return b
}
