/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "sample-controller-k8s/pkg/apis/appreplica/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppReplicas implements AppReplicaInterface
type FakeAppReplicas struct {
	Fake *FakeNextgenV1alpha1
	ns   string
}

var appreplicasResource = schema.GroupVersionResource{Group: "nextgen.k8s.test", Version: "v1alpha1", Resource: "appreplicas"}

var appreplicasKind = schema.GroupVersionKind{Group: "nextgen.k8s.test", Version: "v1alpha1", Kind: "AppReplica"}

// Get takes name of the appReplica, and returns the corresponding appReplica object, and an error if there is any.
func (c *FakeAppReplicas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AppReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appreplicasResource, c.ns, name), &v1alpha1.AppReplica{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppReplica), err
}

// List takes label and field selectors, and returns the list of AppReplicas that match those selectors.
func (c *FakeAppReplicas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AppReplicaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appreplicasResource, appreplicasKind, c.ns, opts), &v1alpha1.AppReplicaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AppReplicaList{ListMeta: obj.(*v1alpha1.AppReplicaList).ListMeta}
	for _, item := range obj.(*v1alpha1.AppReplicaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appReplicas.
func (c *FakeAppReplicas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appreplicasResource, c.ns, opts))

}

// Create takes the representation of a appReplica and creates it.  Returns the server's representation of the appReplica, and an error, if there is any.
func (c *FakeAppReplicas) Create(ctx context.Context, appReplica *v1alpha1.AppReplica, opts v1.CreateOptions) (result *v1alpha1.AppReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appreplicasResource, c.ns, appReplica), &v1alpha1.AppReplica{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppReplica), err
}

// Update takes the representation of a appReplica and updates it. Returns the server's representation of the appReplica, and an error, if there is any.
func (c *FakeAppReplicas) Update(ctx context.Context, appReplica *v1alpha1.AppReplica, opts v1.UpdateOptions) (result *v1alpha1.AppReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appreplicasResource, c.ns, appReplica), &v1alpha1.AppReplica{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppReplica), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppReplicas) UpdateStatus(ctx context.Context, appReplica *v1alpha1.AppReplica, opts v1.UpdateOptions) (*v1alpha1.AppReplica, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(appreplicasResource, "status", c.ns, appReplica), &v1alpha1.AppReplica{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppReplica), err
}

// Delete takes name of the appReplica and deletes it. Returns an error if one occurs.
func (c *FakeAppReplicas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(appreplicasResource, c.ns, name, opts), &v1alpha1.AppReplica{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppReplicas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appreplicasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AppReplicaList{})
	return err
}

// Patch applies the patch and returns the patched appReplica.
func (c *FakeAppReplicas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AppReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appreplicasResource, c.ns, name, pt, data, subresources...), &v1alpha1.AppReplica{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AppReplica), err
}
