apiVersion: v1
kind: Namespace
metadata:
  name: sample-replica-mangaal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appreplica-cluster-role
rules:
- apiGroups:
  - nextgen.k8s.test
  resources:
  - appreplicas
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*" 
- apiGroups:
  - nextgen.k8s.test
  resources:
  - appreplicas/finalizers
  verbs:
  - update
- apiGroups:
  - nextgen.k8s.test
  resources:
  - appreplicas/status
  verbs:
  - get
  - patch
  - update   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appreplica-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: replica-controller-sa
  namespace: sample-replica-mangaal
roleRef:
  kind: ClusterRole
  name: appreplica-cluster-role
  apiGroup: rbac.authorization.k8s.io
