/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"
	v1alpha1 "sample-controller-k8s/pkg/apis/myappdeployment/v1alpha1"
	myappdeploymentv1alpha1 "sample-controller-k8s/pkg/clinet/applyconfiguration/myappdeployment/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMyAppDeployments implements MyAppDeploymentInterface
type FakeMyAppDeployments struct {
	Fake *FakeNextgenV1alpha1
	ns   string
}

var myappdeploymentsResource = v1alpha1.SchemeGroupVersion.WithResource("myappdeployments")

var myappdeploymentsKind = v1alpha1.SchemeGroupVersion.WithKind("MyAppDeployment")

// Get takes name of the myAppDeployment, and returns the corresponding myAppDeployment object, and an error if there is any.
func (c *FakeMyAppDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MyAppDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(myappdeploymentsResource, c.ns, name), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// List takes label and field selectors, and returns the list of MyAppDeployments that match those selectors.
func (c *FakeMyAppDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MyAppDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(myappdeploymentsResource, myappdeploymentsKind, c.ns, opts), &v1alpha1.MyAppDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MyAppDeploymentList{ListMeta: obj.(*v1alpha1.MyAppDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.MyAppDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested myAppDeployments.
func (c *FakeMyAppDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(myappdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a myAppDeployment and creates it.  Returns the server's representation of the myAppDeployment, and an error, if there is any.
func (c *FakeMyAppDeployments) Create(ctx context.Context, myAppDeployment *v1alpha1.MyAppDeployment, opts v1.CreateOptions) (result *v1alpha1.MyAppDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(myappdeploymentsResource, c.ns, myAppDeployment), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// Update takes the representation of a myAppDeployment and updates it. Returns the server's representation of the myAppDeployment, and an error, if there is any.
func (c *FakeMyAppDeployments) Update(ctx context.Context, myAppDeployment *v1alpha1.MyAppDeployment, opts v1.UpdateOptions) (result *v1alpha1.MyAppDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(myappdeploymentsResource, c.ns, myAppDeployment), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMyAppDeployments) UpdateStatus(ctx context.Context, myAppDeployment *v1alpha1.MyAppDeployment, opts v1.UpdateOptions) (*v1alpha1.MyAppDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(myappdeploymentsResource, "status", c.ns, myAppDeployment), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// Delete takes name of the myAppDeployment and deletes it. Returns an error if one occurs.
func (c *FakeMyAppDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(myappdeploymentsResource, c.ns, name, opts), &v1alpha1.MyAppDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMyAppDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(myappdeploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MyAppDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched myAppDeployment.
func (c *FakeMyAppDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MyAppDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(myappdeploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied myAppDeployment.
func (c *FakeMyAppDeployments) Apply(ctx context.Context, myAppDeployment *myappdeploymentv1alpha1.MyAppDeploymentApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MyAppDeployment, err error) {
	if myAppDeployment == nil {
		return nil, fmt.Errorf("myAppDeployment provided to Apply must not be nil")
	}
	data, err := json.Marshal(myAppDeployment)
	if err != nil {
		return nil, err
	}
	name := myAppDeployment.Name
	if name == nil {
		return nil, fmt.Errorf("myAppDeployment.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(myappdeploymentsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeMyAppDeployments) ApplyStatus(ctx context.Context, myAppDeployment *myappdeploymentv1alpha1.MyAppDeploymentApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.MyAppDeployment, err error) {
	if myAppDeployment == nil {
		return nil, fmt.Errorf("myAppDeployment provided to Apply must not be nil")
	}
	data, err := json.Marshal(myAppDeployment)
	if err != nil {
		return nil, err
	}
	name := myAppDeployment.Name
	if name == nil {
		return nil, fmt.Errorf("myAppDeployment.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(myappdeploymentsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.MyAppDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MyAppDeployment), err
}
